version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz
            command: timeout 1m lscpu
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz
            command: timeout 1m lscpu
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz
            command: timeout 1m lscpu
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz
            command: timeout 1m lscpu
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3